name = "photos-backup"
main = "worker.js"
compatibility_date = "2026-05-14"

[[kv_namespaces]]
binding = "PHOTOS_BACKUP_KV"
id = "782d4468f767496fbb9a382ccf6bea4d"

[observability]
enabled = true

  [observability.logs]
  invocation_logs = true
  head_sampling_rate = 1